- name: Install Kali tools
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - vault.yml
  vars:
    ansible_become_pass: "{{ vault_root_pw }}"
  roles:
    - env-settings
    - dev-tools
    - role: ext-tools
      vars:
        h_tools_base: "/home/kali/hacking_tools"
