- name: Install Kali
  hosts: localhost
  become: yes
  vars_files:
    - vault.yml
  vars:
    ansible_become_pass: "{{ root_pw }}"

  tasks:
    - name: Install apt keys
      apt_key:
        url: "{{ item }}"
        state: present
      loop: [
        "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg",
        "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc",
      ]

    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: [
        "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main",
        "deb https://deb.torproject.org/torproject.org stretch main",
      ]

    - name: Install tools (apt)
      apt: 
        name: "{{ item }}" 
        state: present
        update_cache: yes
      loop: [git, codium, tmux, tor, afl, gdb, docker.io, apktool, foremost, exiftool, gobuster]

    - name: Install tools (gem)
      gem:
        name: "{{ item }}"
        state: latest
      loop: [zsteg]

    - name: Create missing folders
      file:
        path: "{{ item }}"
        owner: kali
        group: kali
        mode: "0755"
        state: directory
      loop: ["/home/kali/tools"]

    - name: Install tools from Github
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        clone: yes
        update: yes
      loop: [
        {repo: "https://github.com/hak5darren/USB-Rubber-Ducky", dest: /home/kali/tools/RubberDucky},
        {repo: "https://github.com/danielmiessler/SecLists", dest: /home/kali/tools/SecLists}
      ]

    - name: Set bash_aliases
      template:
        src: .bash_aliases.j2
        dest: /home/kali/.bash_aliases
        owner: kali
        group: kali
        mode: "0644"

    - name: Check if rockyou.txt.gz exists
      stat:
        path: /usr/share/wordlists/rockyou.txt.gz
      register: rockyou_exists

    - name: Decompress rockyou.txt.gz
      shell:
        cmd: gzip -d /usr/share/wordlists/rockyou.txt.gz
      when: rockyou_exists == true
