---
# tasks file for ext-tools
- name: Install apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: [
    "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc",
  ]

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: [
    "deb https://deb.torproject.org/torproject.org stretch main",
  ]

- name: Install tools
  apt: 
    name: "{{ item }}" 
    state: present
    update_cache: yes
  loop: [tor]

- name: Create missing folders
  file:
    path: "{{ item }}"
    owner: kali
    group: kali
    mode: "0755"
    state: directory
  loop: ["{{ h_tools_base }}"]

- name: Install tools from Github
  git:
    repo: "{{ item.repo }}"
    dest: "{{ h_tools_base }}/{{ item.dest }}"
    clone: yes
    update: yes
    force: yes
  loop: [
    {repo: "https://github.com/hak5darren/USB-Rubber-Ducky", dest: RubberDucky},
    {repo: "https://github.com/danielmiessler/SecLists", dest: SecLists}
  ]