---
# tasks file for ext-tools
- name: Create missing folders
  file:
    path: "{{ item }}"
    owner: kali
    group: kali
    mode: "0755"
    state: directory
  loop: ["{{ h_tools_base }}"]

- name: Install tools from Github
  git:
    repo: "{{ item.repo }}"
    dest: "{{ h_tools_base }}/{{ item.dest }}"
    clone: yes
    update: yes
    force: yes
  loop: [
    {repo: "https://github.com/hak5darren/USB-Rubber-Ducky", dest: RubberDucky},
    {repo: "https://github.com/danielmiessler/SecLists", dest: SecLists}
  ]