---
# tasks file for dev-tools
- name: Install apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: [
    "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg",
  ]

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: [
    "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main",
  ]

- name: Install tools
  apt: 
    name: "{{ item }}" 
    state: present
    update_cache: yes
  loop: [git, codium, tmux]